targetPath: ./monitor_yig_exporter/collector/
host: 192.168.2.128
mysql:
  - itemId: tidb_4000
    dataSourceName: root:@tcp(192.168.2.128:4000)/yig?charset=utf8
redis:
  - itemId: redis_6379
    addr: 192.168.2.128:6379
    password: hehehehe
process:
  - itemId: mtail_01
    serviceName: mtail
  - itemId: yigbilling_01
    serviceName: yig-billing
tcp:
  - itemId: yig_8080
    addr: 192.168.2.128:8080
  - itemId: yig_9000
    addr: 192.168.2.128:9000
