targetPath: ./monitor_yig_exporter/collector/
host: 192.168.2.128
mysql:
  - itemId: tidb_4000
    dataSourceName: root:@tcp(192.168.2.128:4000)/yig?charset=utf8
redis:
  - itemId: redis_6379
    addr: 192.168.2.128:6379
    password: hehehehe
http:
  - itemId: Iam_01
    method: GET
    url: http://192.168.2.128:8888/hello?user=admin&pass=888
    headers: ["Accept-Language:zh-cn,en","dsafaf:fsvfds"]
  - itemId: PostPay_01
    method: HEAD
    url: http://192.168.2.128:7777/hello?user=admin&pass=777
    headers: ["Accept-Language:zh-cn,zh","Accept-Encoding:gzip,deflate","fhdsvhodv:fdsvfsv","Cookie:JSESSIONID=369766FDF6220F7803433C0B2DE36D98"]
process:
  - itemId: dnsmasq_01
    serviceName: dnsmasq
tcp:
  - itemId: yig_8080
    addr: 192.168.2.128:8080
  - itemId: yig_9000
    addr: 192.168.2.128:9000
