targetPath: ./node_exporter/collector/
databases:
 - databaseId: 1
   databaseNodes:
   - fileName: tidb_monitor.go
     name: tidb
     dataSourceName: root:@tcp(192.168.2.128:4000)/yig?charset=utf8
     fqName: tidb_status
     variableLabels: status
     labelValues: tidb
caches:
  - cacheId: 1
    cacheNodes:
      - fileName: redis_monitor.go
        name: redis
        addr: 192.168.2.128:6379
        password: hehehehe
        fqName: redis_status
        variableLabels: status
        labelValues: redis
httpservers:
  - httpId: 1
    httpNodes:
      - fileName: iam_api_monitor.go
        name: iam
        reqWay: GET
        url: http://192.168.2.128:8888/hello?user=admin&pass=888
        reqHead: Accept-Language:zh-cn,en|
        fqName: iam_status
        variableLabels: status
        labelValues: iam
  - httpId: 2
    httpNodes:
      - fileName: postPay_api_monitor.go
        name: postPay
        reqWay: HEAD
        url: http://192.168.2.128:7777/hello?user=admin&pass=777
        reqHead: Accept-Language:zh-cn,zh|Accept-Encoding:gzip,deflate|Cookie:JSESSIONID=369766FDF6220F7803433C0B2DE36D98
        fqName: postPay_status
        variableLabels: status
        labelValues: postPay
processes:
  - processId: 1
    processNodes:
      - fileName: process_monitor.go
        name: dnsmasq
        fqName: dnsmasq_status
        variableLabels: status
        labelValues: dnsmasq
tcps:
  - tcpId: 1
    tcpNodes:
      - fileName: tcp1_monitor.go
        name: tcp1
        addr: 192.168.2.128:9888
        fqName: tcp1_status
        variableLabels: status
        labelValues: tcp
  - tcpId: 1
    tcpNodes:
      - fileName: tcp2_monitor.go
        name: tcp2
        addr: 192.168.2.128:9887
        fqName: tcp2_status
        variableLabels: status
        labelValues: tcp
